# Generated by Django 5.2.6 on 2025-10-14 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'verbose_name': 'One Time Password',
                'verbose_name_plural': 'One Time Password',
            },
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_email_6f2530_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_is_acti_a79dc0_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='users_userr_user_id_6be9a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='userrole',
            name='users_userr_role_id_3052a3_idx',
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='otp',
            unique_together={('otp', 'user')},
        ),
    ]
