# Generated by Django 5.2.6 on 2025-10-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp_alter_role_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
