# Generated by Django 5.2.6 on 2025-10-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_otp_is_used_alter_otp_otp'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='permission',
            name='users_permi_code_na_e52519_idx',
        ),
        migrations.RemoveIndex(
            model_name='permission',
            name='users_permi_is_acti_f1128a_idx',
        ),
        migrations.AlterField(
            model_name='permission',
            name='code_name',
            field=models.CharField(help_text="Unique identifier for the permission eg 'can_view_products'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='permissioncategory',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='permissioncategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
