# Generated by Django 5.2.6 on 2025-10-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_permission_users_permi_code_na_e52519_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
