# Generated by Django 5.2.6 on 2025-10-31 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
