# Generated by Django 5.2.6 on 2025-10-09 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_stripepaymentintent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='stripe_customer_id',
        ),
        migrations.DeleteModel(
            name='StripePaymentIntent',
        ),
    ]
