# Generated by Django 5.2.6 on 2025-10-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_permissioncategory_permission_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='address_descripton',
            new_name='address_description',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
