# Generated by Django 5.2.6 on 2025-11-01 17:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reply',
            unique_together={('seller', 'reviewer')},
        ),
    ]
