# Generated by Django 5.2.6 on 2025-11-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_reply_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'replies'},
        ),
    ]
