# Generated by Django 5.2.6 on 2025-10-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='purchased',
            new_name='is_paid',
        ),
    ]
