# Generated by Django 5.2.6 on 2025-10-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_purchased_cartitem_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='is_paid',
        ),
    ]
