# Generated by Django 5.2.6 on 2025-11-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_is_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
