# Generated by Django 5.2.6 on 2025-11-03 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitems_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'ordering': ['id']},
        ),
    ]
