# Generated by Django 5.2.6 on 2025-11-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
    ]
