# Generated by Django 5.2.6 on 2025-11-04 09:37

import datetime
import django.utils.timezone
import orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('code_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_count', models.PositiveBigIntegerField()),
                ('percentage_off', models.IntegerField(validators=[orders.validators.percentage_validator])),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(default=datetime.timedelta(days=7))),
            ],
        ),
    ]
