# Generated by Django 5.2.6 on 2025-11-04 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 9, 52, 28, 337891, tzinfo=datetime.timezone.utc)),
        ),
    ]
