# Generated by Django 5.2.6 on 2026-01-28 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_discount_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='to_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 4, 10, 38, 8, 709593, tzinfo=datetime.timezone.utc)),
        ),
    ]
