# Generated by Django 5.2.6 on 2025-10-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='additional_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
