# Generated by Django 5.2.6 on 2025-10-30 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.BigIntegerField(default=1),
        ),
    ]
