# Generated by Django 5.2.6 on 2025-11-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0.0, help_text='Average of product ratings'),
        ),
        migrations.AddField(
            model_name='product',
            name='review_count',
            field=models.PositiveBigIntegerField(default=0, help_text='Number of reviews'),
        ),
    ]
