# Generated by Django 5.2.6 on 2025-09-17 01:45

import products.model_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_additional_info_alter_product_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[products.model_validators.validate_price]),
        ),
    ]
